### ISSUE TITLE
IndexError: list assignment index out of range

### ISSUE THREAD

**Issue by jchen-sinai** [plessbd/ocflzw-decompress#3]
When decompress a big blob, and I got the following error. The blob_length is "501166".
===========
    for bt in lzw.decompress(blob_content):
  File "/usr/local/lib/python3.10/dist-packages/ocflzw_decompress/lzw.py", line 69, in decompress
    self.SaveItemToLookupTable(lookupIndex)
  File "/usr/local/lib/python3.10/dist-packages/ocflzw_decompress/lzw.py", line 92, in SaveItemToLookupTable
    self.tempDecompressBuffer[self.tempBufferIndex] = self.lzwLookupTable[compressedCode].Suffix
IndexError: list assignment index out of range
==============

**Comment by plessbd** [comment]
this is probably related to #2 
If you can share the blobs it is trying to decompress we might be able to help figure out the issue.

**Comment by plessbd** [comment]
also, please look at #4  which had similar issues while I work to update the documentation.
