### ISSUE TITLE
How to obtain compressed_base64

### ISSUE THREAD

**Issue by vrajbillings** [plessbd/ocflzw-decompress#5]
Hi @plessbd 
Thanks for providing a python port.
I am trying to run this against a ce_blob data. I wanted to ask how did you obtain the compressed_base64 value of the blob?
for example if you do:
`Select blob_contents from CE_BLOB where event_id in (integer)` this gives me an object so how did you go from object to compressed_base64?

**Comment by plessbd** [comment]
Sorry @vrajbillings  I did not see your message

We did the same for the select.
We used cx_Oracle to connect and after running our select we just did a `.read()` on the column
